secrets:
  nginx_email:
    file: $SECRETSDIR/nginx_email
  nginx_password:
    file: $SECRETSDIR/nginx_password
  
  postgres_db:
    file: $SECRETSDIR/postgres_db
  postgres_user:
    file: $SECRETSDIR/postgres_user
  postgres_password:
    file: $SECRETSDIR/postgres_password

services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - "127.0.0.1:3080:3080"
    depends_on:
      - mongodb
      - rag_api
    restart: unless-stopped
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
  
  client:
    image: jc21/nginx-proxy-manager:latest
    container_name: LibreChat-NGINX
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "10.6.3.1:81:81"
    depends_on:
      - api
    secrets:
      - nginx_email
      - nginx_password
    environment:
      INITIAL_ADMIN_EMAIL__FILE: /run/secrets/nginx_email
      INITIAL_ADMIN_PASSWORD__FILE: /run/secrets/nginx_password
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.7:/meili_data

  vectordb:
    image: ankane/pgvector:latest
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    restart: unless-stopped
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: unless-stopped
    depends_on:
      - vectordb
    env_file:
      - .env
  
volumes:
  pgdata2:
